on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: deploy2nekoweb
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # build step

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install 11ty
        run: npm install @11ty/eleventy

      - name: Pre-build steps
        run: rm -rf site/*

      - name: Build site
        run: npx @11ty/eleventy

      # deploy

      - name: deploy2nekoweb
        uses: indiefellas/deploy2nekoweb@main
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-domain: "furshark.net"
          nekoweb-username: "sharkyfur"
          directory: "site"
